if &t_Co > 1 || has("gui_running")
  syntax on
  set number
  set termguicolors

  function! ApplyColorScheme()
    if empty($SSH_CLIENT) && empty($SSH_TTY)
      let l:cs = trim(system("gsettings get org.freedesktop.appearance color-scheme 2>/dev/null"))
      if l:cs == ""
        let l:cs = trim(system("gsettings get org.gnome.desktop.interface color-scheme 2>/dev/null"))
      endif
      if l:cs == "'prefer-dark'"
        set background=dark
      else
        set background=light
      endif
    endif

    colorscheme gruvbox
  endfunction

  call ApplyColorScheme()
  command! Rescheme call s:ApplyColorSchemeAndBackground()
  if has('nvim')
"    autocmd FocusGained * call ApplyColorScheme() " avoid as it causes flicker
    lua << EOF
  vim.uv.new_signal():start("sigusr1", vim.schedule_wrap(function()
    vim.cmd("call ApplyColorScheme()")
  end))
EOF
  endif
endif

if has("gui_running")
  set guifont=Lucida_Console:h9:cDEFAULT
  set guicursor=a:blinkon0
  set guioptions=bgmprT
  set encoding=utf-8
endif

if has('nvim')
  " nvim controls the mouse, so emulate terminal behaviour of yanking into
  " primary X11 paste buffer.
  xnoremap <silent> <LeftRelease> "*ygv
  nnoremap <silent> <2-LeftMouse> <2-LeftMouse>"*ygv
  xnoremap <silent> <2-LeftMouse> <Esc><2-LeftMouse>"*ygv
  nnoremap <silent> <3-LeftMouse> <3-LeftMouse>"*ygv
  xnoremap <silent> <3-LeftMouse> <Esc><3-LeftMouse>"*ygv
endif

set tabstop=2
set expandtab
set shiftwidth=2
au FileType python setl ts=4 sw=4 et

set backspace=indent,eol,start
set nolist
set listchars=tab:\|-,trail:#
set showmatch
set linebreak
set ruler
" Nope, only a single space after a sentence ends:
set cpoptions-=J
set nojoinspaces

" DO NOT WRAP LINES AUTOMATICALLY
set textwidth=0 wrapmargin=0

set showcmd
set history=256
set viminfo='100,\"256
set autoindent

set hlsearch
set incsearch

set tw=0

" Space == next page
nmap <Space> 

" <F10> = toggle match highlighting
nmap <F10> :set hls!<CR>

" Suppress all spaces at end/beginning of lines
nmap _s :%s/\s\+$//<CR>
nmap _S :%s/^\s\+//<CR>
nmap _v :%s/^\s+$//<CR>

" quick disable auto-intent magic (formerly: mis-use vim paste-toggle for it)
function! ToggleIndent()
  if &autoindent || &smartindent || &cindent || !empty(&indentexpr)
    let g:saved_indentexpr = &l:indentexpr
    setlocal noautoindent nosmartindent nocindent indentexpr=
  else
    let &l:indentexpr = get(g:, 'saved_indentexpr', '')
    setlocal autoindent smartindent
  endif
endfunction
inoremap qP <Cmd>call ToggleIndent()<CR>

" Shift-Up,Down,Home,End: Move inside wrapped lines
inoremap <buffer> <silent> <S-Up>   <C-o>gk
inoremap <buffer> <silent> <S-Down> <C-o>gj
inoremap <buffer> <silent> <S-Home> <C-o>g<Home>
inoremap <buffer> <silent> <S-End>  <C-o>g<End>
" Workaround for broken embedded FW on X210ai:
inoremap <buffer> <silent> gT >
inoremap <buffer> <silent> lT <
inoremap <buffer> <silent> pP \|
inoremap <buffer> <silent> Nb #
inoremap <buffer> <silent> tT '

" move current line up/down
nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

" :sudow: sudo write a file (resets permissions?)
cnoremap sudow w !sudo tee % >/dev/null

" highlight too long lines
"autocmd BufWinEnter *.c let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)
"autocmd BufWinLeave *.c call matchdelete(w:m2)

" permanently highlight 80th column
" set colorcolumn=80

" highlight trailing whitespace and tabs after spaces in leading whitespace
highlight ExtraWhitespace ctermbg=red guibg=red
autocmd BufWinEnter *.c match ExtraWhitespace /^\s*   \|\s\+$/
autocmd InsertEnter *.c match ExtraWhitespace /^\s*   \|\s\+\%#\@<!$/
autocmd InsertLeave *.c match ExtraWhitespace /^\s*   \|\s\+$/
autocmd BufWinLeave *.c call clearmatches()

" Sort words of a line
command! -nargs=0 -range SortLine <line1>,<line2>call setline('.',join(sort(split(getline('.'),' ')),' '))

" ex command for toggling hex mode
command -bar Hexmode call ToggleHex()

" helper function to toggle hex mode
function ToggleHex()
  " hex mode should be considered a read-only operation
  " save values for modified and read-only for restoration later,
  " and clear the read-only flag for now
  let l:modified=&mod
  let l:oldreadonly=&readonly
  let &readonly=0
  let l:oldmodifiable=&modifiable
  let &modifiable=1
  if !exists("b:editHex") || !b:editHex
    " save old options
    let b:oldft=&ft
    let b:oldbin=&bin
    " set new options
    setlocal binary " make sure it overrides any textwidth, etc.
    silent :e " this will reload the file without trickeries
              "(DOS line endings will be shown entirely )
    let &ft="xxd"
    " set status
    let b:editHex=1
    " switch to hex editor
    %!xxd
  else
    " restore old options
    let &ft=b:oldft
    if !b:oldbin
      setlocal nobinary
    endif
    " set status
    let b:editHex=0
    " return to normal editing
    %!xxd -r
  endif
  " restore values for modified and read only state
  let &mod=l:modified
  let &readonly=l:oldreadonly
  let &modifiable=l:oldmodifiable
endfunction

